name: shelf_swap
description: Server side rendering for Flutter.
homepage: https://github.com/Flutter-Swap/dart
version: 0.0.2-dev.6
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  dart_frog: ^1.1.0
  swap: 
    path: ../swap

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
